MSA-744: Display inactive future dates and display time and date in t…
softwaregroup-bg/ut-front-react pull request #570
Opened 2021-08-23 09:46 UTC by NKozhuharski

@stoberov @pavelGeorgievSG

2021-08-24 05:58 UTC, stoberov commented
@NKozhuharski - DatePicker-ите са компоненти, които традиционно си пазят state-a сами в себе си. В определени случаи, value/onChange могат да им се подават като props-ове. Обаче това да се използва setState, за да поддържаш state-a на подобни компоненти - е или лоша практика, или не съм го виждал. Бих ограничил фикса до употребата на maxDate.

2021-08-24 14:10 UTC, NKozhuharski commented
Здравейте, @stoberov @kalinkrustev пускам линк към sandbox - https://codesandbox.io/s/material-ui-pickers-usage-demo-o7oojxx1pq?from-embed=&file=/src/App.jsx:260-276 за съжаление не тръгва без пропъртито onChange. Не мога също да оставя само едно пропърти във стейта тъи като занулява датата.

2021-08-29 20:09 UTC, NKozhuharski commented
@stoberov , вече работи само с едно пропърти както искаше.

2021-08-30 17:12 UTC, kalinkrustev commented
Мако ми е странно защо отпада defaultValue. Очаквам, че може някъде да се ползва, при което може да счупим нещо. Има ли начин да не променяме съществуваща логика? Ако целим да оправим нещо на конкретно място, то там може да не се подава нищо за defaultValue, при което да се включи новата логика.

2021-08-31 08:27 UTC, NKozhuharski commented
@kalinkrustev Бях забравил да върна оригиналните промени. Не се налага изобщо промяна на defaultValue.

2021-08-31 16:01 UTC, kalinkrustev requested changes

2021-08-31 16:01 UTC, kalinkrustev commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
тук не би трябвало да се ползва за стойност логиката от ред 167, а не днешна дата:?
```js
        const date = defaultValue
            ? new Date(defaultValue)
            : new Date(defaultDate);
```

2021-09-01 15:25 UTC, NKozhuharski commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
Както кажете, така ще го направя,но ако е подадена по голяма дата от днешната ще гърми формата.

2021-09-03 12:17 UTC, kalinkrustev commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
Подаването на по-голяма дата от днешната трябва да е разрешено по дефолт, освен ако отвън на компонента не се конфигурира нещо различно. Промените, които правим не трябва да променят съществуващата логика при съществуващия набор от пропъртита. Новата логика може да се базира на нови комбинаии от пропъртита, комбинации, които преди не са съществували. Освен ако не се цели фикс на бъг, а това не е така, доколкото рабирам от описанието.

2021-09-07 15:27 UTC, NKozhuharski commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
ok, оправено е.

2021-09-08 22:41 UTC, stoberov commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
Според мен е за resolve , тагвам @kalinkrustev

2021-09-14 06:03 UTC, stoberov commented on components/DateTimePicker/Simple/index.js
> +            date: new Date()
Дали има happy-end този казус? :))

2021-09-14 06:41 UTC, kalinkrustev approved these changes

2021-09-14 07:03 UTC, merged