fix(MSA-1185):[USP] Customers/ Document upload: Not user-friendly error returned when document uploaded is too large
softwaregroup-bg/ut-front-react pull request #599
Opened 2022-02-13 14:25 UTC by iammohanselvam

…or returned when document uploaded is too large

2022-02-14 07:23 UTC, BozhidarTodorov approved these changes

2022-02-18 16:25 UTC, stoberov commented
@iammohanselvam - pls, check my last comment from a few days ago.
@BozhidarTodorov - please, add your review.

2022-02-19 08:58 UTC, stoberov requested changes

2022-02-19 08:59 UTC, stoberov commented on components/DocumentUpload/index.js
> +            if (attachmentResult.error.body?.error === 'Request Entity Too Large') {
Абсолютно съм съгласен, бях оставил същия коментар, сега виждам, че не го сейвнало. 
Преведено на английски за Мохан и цъкам Resolve тук :D

2022-02-21 06:33 UTC, iammohanselvam commented on components/DocumentUpload/index.js
> +            if (attachmentResult.error.body?.error === 'Request Entity Too Large') {
Got it, working on it (y)

2022-02-21 07:22 UTC, iammohanselvam commented on components/DocumentUpload/index.js
> +            if (attachmentResult.error.body?.error === 'Request Entity Too Large') {
Hi @stoberov  please verify now.

2022-02-21 07:42 UTC, BozhidarTodorov approved these changes

2022-02-21 16:26 UTC, stoberov commented on components/DocumentUpload/index.js
> +            if (attachmentResult.error.body?.error === 'Request Entity Too Large') {
Lookin' good!

2022-02-22 06:50 UTC, merged