PSTB-6337: Add disabled property.
softwaregroup-bg/ut-front-react pull request #606
Opened 2022-03-15 12:04 UTC by NKozhuharski

2022-03-15 12:06 UTC, NKozhuharski commented
Related MR: https://git.softwaregroup.com/ut5/ut-notice/merge_requests/76

2022-03-15 12:44 UTC, KrasimirGenchev approved these changes

2022-03-16 07:30 UTC, stoberov requested changes

2022-03-16 07:30 UTC, stoberov commented on components/SearchBox/index.js
> +    disabled: PropTypes.bool,
Нещо против да го добавиш и в `defaultProps`? @NKozhuharski

2022-03-16 07:30 UTC, stoberov commented on components/Filters/ByCustomSearch/index.js
> +        const isDisable = !this.props.defaultField;
`isDisable` не звучи достатъчно булево. `isDisabled` може би? @NKozhuharski (ако изобщо има и нужда от променлива.

2022-03-16 08:50 UTC, NKozhuharski commented on components/SearchBox/index.js
> +    disabled: PropTypes.bool,
fixed

2022-03-16 08:50 UTC, NKozhuharski commented on components/Filters/ByCustomSearch/index.js
> +        const isDisable = !this.props.defaultField;
fixed

2022-03-16 09:47 UTC, merged