fix/(MSA-3047): User Management -> Advanced Search
softwaregroup-bg/ut-front-react pull request #661
Opened 2022-10-18 06:01 UTC by KrasimirGenchev

2022-10-18 06:03 UTC, KrasimirGenchev commented
https://git.softwaregroup.com/ut5/ut-user/merge_requests/2260

2022-10-18 07:39 UTC, stoberov requested changes

2022-10-18 07:39 UTC, stoberov commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Нямам по-добро предложение (не съм вникнал в проблема), но ще съм Mr Obvious като кажа, че не ми звучи добра идея в компонент, който се използва на много места (GridToolBox), да се вкарват строго-специфични пропъртита, заради един конкретен репорт (User Management) :( Че даже и 3 на брой :( 

Дали не може да се помисли за нещо по-абстрактно? Това, че останалите 3-4 филтъра си работят, а само тези 2та не работят , също ми е съмнително.

2022-10-18 08:05 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Проблема е, че трябва да използваме мачването което се прави в approveValueStatusMap и approveValueUsersMap и затова ги подавам като пропъртита. Естествено могат да се напишат в същия файл или отделен хелпър но тогава има риск ако се промени само единия файл да се появи разлика в работата на филтъра ако се избира от тулбокса или адванс сърча.

2022-10-19 06:16 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Когато сетваме филтър през адванс сърча updateFilters в ut-user не се използва. Ако искаш да се чуем в Skype ?

2022-10-20 06:51 UTC, stoberov commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Пиши/звънни по някое време :D

2022-10-20 07:48 UTC, stambata commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Не може да има property, наречено `userGridFilter` в `GridToolBox` компонента

2022-10-20 08:46 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Махнах го.

2022-10-20 11:09 UTC, stoberov commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Ако аз кажа "не може да има property, наречено `approveValueUsersMap` и `approveValueStatusMap`" - ще има ли същият ефект за махането им? 😄

2022-10-20 12:25 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Без userGridFilter  мога да постигна същия ефект с промяната от последния къмит, но без approveValueUsersMap и approveValueStatusMap няма как да го направя :)

2022-10-20 12:42 UTC, stambata commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
не може ли да има просто само 1 property, което да се подава отвън. Например `filtersOverride`
и да има някаква такава структура:
```
{
    status: {
        objectKey1: satusValue1,
        objectKey2: satusValue2,
        ...
    },
    userType: {
        objectKey1: userTypeValue1,
        objectKey2: userTypeValue2,
        ...
    }
}
```

2022-10-20 15:14 UTC, stambata commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
пак е хардкоднато така. очаква да има конкретно `status` и `userType`. Не е добре да бъде така в general purpose компонент. По-добре да се направи някаква абстракция отколкото да се хардкодва спрямо конкретни нужди. Виж този [Pull request](https://github.com/softwaregroup-bg/ut-front-react/pull/663)
Не съм го тествал, но с илюстративна цел...

2022-10-21 10:20 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +                        result[override.key || key] = (override.value !== null && override.value !== undefined) ? override.value : override;
Написах го по този начин, защото даваше грешка при компилирането ако беше записано с ??

2022-10-21 10:21 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +    approveValueStatusMap: PropTypes.array,
Fixed

2022-10-21 11:14 UTC, stambata commented on components/GridToolBox/index.js
> +                        result[override.key || key] = (override.value !== null && override.value !== undefined) ? override.value : override;
ама работи ли?

2022-10-21 11:28 UTC, KrasimirGenchev commented on components/GridToolBox/index.js
> +                        result[override.key || key] = (override.value !== null && override.value !== undefined) ? override.value : override;
да, работи. Ако ти остане минута мога да демонстрирам :)

2022-10-21 11:37 UTC, kalinkrustev commented on components/GridToolBox/index.js
> +                        result[override.key || key] = (override.value !== null && override.value !== undefined) ? override.value : override;
само кажете като всички са доволни, да го приема

2022-10-21 11:49 UTC, stoberov commented on components/GridToolBox/index.js
> +                        result[override.key || key] = (override.value !== null && override.value !== undefined) ? override.value : override;
Аз съм доволен :D

2022-10-21 12:05 UTC, stambata approved these changes

2022-10-21 12:17 UTC, stoberov approved these changes

2022-10-21 13:45 UTC, merged